#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCalendar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataBase")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTabela_Kategorie(Tabela_Kategorie instance);
    partial void UpdateTabela_Kategorie(Tabela_Kategorie instance);
    partial void DeleteTabela_Kategorie(Tabela_Kategorie instance);
    partial void InsertTabela_RL(Tabela_RL instance);
    partial void UpdateTabela_RL(Tabela_RL instance);
    partial void DeleteTabela_RL(Tabela_RL instance);
    partial void InsertTabela_Wydarzenia(Tabela_Wydarzenia instance);
    partial void UpdateTabela_Wydarzenia(Tabela_Wydarzenia instance);
    partial void DeleteTabela_Wydarzenia(Tabela_Wydarzenia instance);
    partial void InsertTabela_WydarzeniaUdostepnione(Tabela_WydarzeniaUdostepnione instance);
    partial void UpdateTabela_WydarzeniaUdostepnione(Tabela_WydarzeniaUdostepnione instance);
    partial void DeleteTabela_WydarzeniaUdostepnione(Tabela_WydarzeniaUdostepnione instance);
        #endregion
        public DataClassesDataContext() :
                base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DataBaseConnectionString2"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tabela_Kategorie> Tabela_Kategorie
		{
			get
			{
				return this.GetTable<Tabela_Kategorie>();
			}
		}
		
		public System.Data.Linq.Table<Tabela_RL> Tabela_RL
		{
			get
			{
				return this.GetTable<Tabela_RL>();
			}
		}
		
		public System.Data.Linq.Table<Tabela_Wydarzenia> Tabela_Wydarzenia
		{
			get
			{
				return this.GetTable<Tabela_Wydarzenia>();
			}
		}
		
		public System.Data.Linq.Table<Tabela_WydarzeniaUdostepnione> Tabela_WydarzeniaUdostepnione
		{
			get
			{
				return this.GetTable<Tabela_WydarzeniaUdostepnione>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabela_Kategorie")]
	public partial class Tabela_Kategorie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nazwa;
		
		private EntitySet<Tabela_Wydarzenia> _Tabela_Wydarzenia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    #endregion
		
		public Tabela_Kategorie()
		{
			this._Tabela_Wydarzenia = new EntitySet<Tabela_Wydarzenia>(new Action<Tabela_Wydarzenia>(this.attach_Tabela_Wydarzenia), new Action<Tabela_Wydarzenia>(this.detach_Tabela_Wydarzenia));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabela_Kategorie_Tabela_Wydarzenia", Storage="_Tabela_Wydarzenia", ThisKey="Id", OtherKey="Id_Kategorii")]
		public EntitySet<Tabela_Wydarzenia> Tabela_Wydarzenia
		{
			get
			{
				return this._Tabela_Wydarzenia;
			}
			set
			{
				this._Tabela_Wydarzenia.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tabela_Wydarzenia(Tabela_Wydarzenia entity)
		{
			this.SendPropertyChanging();
			entity.Tabela_Kategorie = this;
		}
		
		private void detach_Tabela_Wydarzenia(Tabela_Wydarzenia entity)
		{
			this.SendPropertyChanging();
			entity.Tabela_Kategorie = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabela_RL")]
	public partial class Tabela_RL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Email;
		
		private string _Haslo;
		
		private System.Data.Linq.Binary _Sol;
		
		private EntitySet<Tabela_Wydarzenia> _Tabela_Wydarzenia;
		
		private EntitySet<Tabela_WydarzeniaUdostepnione> _Tabela_WydarzeniaUdostepnione;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnHasloChanging(string value);
    partial void OnHasloChanged();
    partial void OnSolChanging(System.Data.Linq.Binary value);
    partial void OnSolChanged();
    #endregion
		
		public Tabela_RL()
		{
			this._Tabela_Wydarzenia = new EntitySet<Tabela_Wydarzenia>(new Action<Tabela_Wydarzenia>(this.attach_Tabela_Wydarzenia), new Action<Tabela_Wydarzenia>(this.detach_Tabela_Wydarzenia));
			this._Tabela_WydarzeniaUdostepnione = new EntitySet<Tabela_WydarzeniaUdostepnione>(new Action<Tabela_WydarzeniaUdostepnione>(this.attach_Tabela_WydarzeniaUdostepnione), new Action<Tabela_WydarzeniaUdostepnione>(this.detach_Tabela_WydarzeniaUdostepnione));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Haslo", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Haslo
		{
			get
			{
				return this._Haslo;
			}
			set
			{
				if ((this._Haslo != value))
				{
					this.OnHasloChanging(value);
					this.SendPropertyChanging();
					this._Haslo = value;
					this.SendPropertyChanged("Haslo");
					this.OnHasloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sol", DbType="VarBinary(64)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Sol
		{
			get
			{
				return this._Sol;
			}
			set
			{
				if ((this._Sol != value))
				{
					this.OnSolChanging(value);
					this.SendPropertyChanging();
					this._Sol = value;
					this.SendPropertyChanged("Sol");
					this.OnSolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabela_RL_Tabela_Wydarzenia", Storage="_Tabela_Wydarzenia", ThisKey="Id", OtherKey="Id_Uzytkownika")]
		public EntitySet<Tabela_Wydarzenia> Tabela_Wydarzenia
		{
			get
			{
				return this._Tabela_Wydarzenia;
			}
			set
			{
				this._Tabela_Wydarzenia.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabela_RL_Tabela_WydarzeniaUdostepnione", Storage="_Tabela_WydarzeniaUdostepnione", ThisKey="Id", OtherKey="Id_Uzytkownika")]
		public EntitySet<Tabela_WydarzeniaUdostepnione> Tabela_WydarzeniaUdostepnione
		{
			get
			{
				return this._Tabela_WydarzeniaUdostepnione;
			}
			set
			{
				this._Tabela_WydarzeniaUdostepnione.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tabela_Wydarzenia(Tabela_Wydarzenia entity)
		{
			this.SendPropertyChanging();
			entity.Tabela_RL = this;
		}
		
		private void detach_Tabela_Wydarzenia(Tabela_Wydarzenia entity)
		{
			this.SendPropertyChanging();
			entity.Tabela_RL = null;
		}
		
		private void attach_Tabela_WydarzeniaUdostepnione(Tabela_WydarzeniaUdostepnione entity)
		{
			this.SendPropertyChanging();
			entity.Tabela_RL = this;
		}
		
		private void detach_Tabela_WydarzeniaUdostepnione(Tabela_WydarzeniaUdostepnione entity)
		{
			this.SendPropertyChanging();
			entity.Tabela_RL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabela_Wydarzenia")]
	public partial class Tabela_Wydarzenia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nazwa;
		
		private System.DateTime _Data;
		
		private System.Nullable<System.TimeSpan> _Godzina;
		
		private string _Opis;
		
		private string _Miejsce;
		
		private string _Goscie;
		
		private string _Notatka;
		
		private string _Kolor;
		
		private int _Priorytet;
		
		private int _Id_Uzytkownika;
		
		private int _Id_Kategorii;
		
		private EntitySet<Tabela_WydarzeniaUdostepnione> _Tabela_WydarzeniaUdostepnione;
		
		private EntityRef<Tabela_Kategorie> _Tabela_Kategorie;
		
		private EntityRef<Tabela_RL> _Tabela_RL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    partial void OnGodzinaChanging(System.Nullable<System.TimeSpan> value);
    partial void OnGodzinaChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    partial void OnMiejsceChanging(string value);
    partial void OnMiejsceChanged();
    partial void OnGoscieChanging(string value);
    partial void OnGoscieChanged();
    partial void OnNotatkaChanging(string value);
    partial void OnNotatkaChanged();
    partial void OnKolorChanging(string value);
    partial void OnKolorChanged();
    partial void OnPriorytetChanging(int value);
    partial void OnPriorytetChanged();
    partial void OnId_UzytkownikaChanging(int value);
    partial void OnId_UzytkownikaChanged();
    partial void OnId_KategoriiChanging(int value);
    partial void OnId_KategoriiChanged();
    #endregion
		
		public Tabela_Wydarzenia()
		{
			this._Tabela_WydarzeniaUdostepnione = new EntitySet<Tabela_WydarzeniaUdostepnione>(new Action<Tabela_WydarzeniaUdostepnione>(this.attach_Tabela_WydarzeniaUdostepnione), new Action<Tabela_WydarzeniaUdostepnione>(this.detach_Tabela_WydarzeniaUdostepnione));
			this._Tabela_Kategorie = default(EntityRef<Tabela_Kategorie>);
			this._Tabela_RL = default(EntityRef<Tabela_RL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="Date NOT NULL")]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Godzina", DbType="Time")]
		public System.Nullable<System.TimeSpan> Godzina
		{
			get
			{
				return this._Godzina;
			}
			set
			{
				if ((this._Godzina != value))
				{
					this.OnGodzinaChanging(value);
					this.SendPropertyChanging();
					this._Godzina = value;
					this.SendPropertyChanged("Godzina");
					this.OnGodzinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NVarChar(200)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miejsce", DbType="NVarChar(200)")]
		public string Miejsce
		{
			get
			{
				return this._Miejsce;
			}
			set
			{
				if ((this._Miejsce != value))
				{
					this.OnMiejsceChanging(value);
					this.SendPropertyChanging();
					this._Miejsce = value;
					this.SendPropertyChanged("Miejsce");
					this.OnMiejsceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Goscie", DbType="NVarChar(200)")]
		public string Goscie
		{
			get
			{
				return this._Goscie;
			}
			set
			{
				if ((this._Goscie != value))
				{
					this.OnGoscieChanging(value);
					this.SendPropertyChanging();
					this._Goscie = value;
					this.SendPropertyChanged("Goscie");
					this.OnGoscieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notatka", DbType="NVarChar(200)")]
		public string Notatka
		{
			get
			{
				return this._Notatka;
			}
			set
			{
				if ((this._Notatka != value))
				{
					this.OnNotatkaChanging(value);
					this.SendPropertyChanging();
					this._Notatka = value;
					this.SendPropertyChanged("Notatka");
					this.OnNotatkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kolor", DbType="NVarChar(20)")]
		public string Kolor
		{
			get
			{
				return this._Kolor;
			}
			set
			{
				if ((this._Kolor != value))
				{
					this.OnKolorChanging(value);
					this.SendPropertyChanging();
					this._Kolor = value;
					this.SendPropertyChanged("Kolor");
					this.OnKolorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priorytet", DbType="Int NOT NULL")]
		public int Priorytet
		{
			get
			{
				return this._Priorytet;
			}
			set
			{
				if ((this._Priorytet != value))
				{
					this.OnPriorytetChanging(value);
					this.SendPropertyChanging();
					this._Priorytet = value;
					this.SendPropertyChanged("Priorytet");
					this.OnPriorytetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Uzytkownika", DbType="Int NOT NULL")]
		public int Id_Uzytkownika
		{
			get
			{
				return this._Id_Uzytkownika;
			}
			set
			{
				if ((this._Id_Uzytkownika != value))
				{
					if (this._Tabela_RL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_UzytkownikaChanging(value);
					this.SendPropertyChanging();
					this._Id_Uzytkownika = value;
					this.SendPropertyChanged("Id_Uzytkownika");
					this.OnId_UzytkownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Kategorii", DbType="Int NOT NULL")]
		public int Id_Kategorii
		{
			get
			{
				return this._Id_Kategorii;
			}
			set
			{
				if ((this._Id_Kategorii != value))
				{
					if (this._Tabela_Kategorie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_KategoriiChanging(value);
					this.SendPropertyChanging();
					this._Id_Kategorii = value;
					this.SendPropertyChanged("Id_Kategorii");
					this.OnId_KategoriiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabela_Wydarzenia_Tabela_WydarzeniaUdostepnione", Storage="_Tabela_WydarzeniaUdostepnione", ThisKey="Id", OtherKey="Id_Wydarzenia")]
		public EntitySet<Tabela_WydarzeniaUdostepnione> Tabela_WydarzeniaUdostepnione
		{
			get
			{
				return this._Tabela_WydarzeniaUdostepnione;
			}
			set
			{
				this._Tabela_WydarzeniaUdostepnione.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabela_Kategorie_Tabela_Wydarzenia", Storage="_Tabela_Kategorie", ThisKey="Id_Kategorii", OtherKey="Id", IsForeignKey=true)]
		public Tabela_Kategorie Tabela_Kategorie
		{
			get
			{
				return this._Tabela_Kategorie.Entity;
			}
			set
			{
				Tabela_Kategorie previousValue = this._Tabela_Kategorie.Entity;
				if (((previousValue != value) 
							|| (this._Tabela_Kategorie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tabela_Kategorie.Entity = null;
						previousValue.Tabela_Wydarzenia.Remove(this);
					}
					this._Tabela_Kategorie.Entity = value;
					if ((value != null))
					{
						value.Tabela_Wydarzenia.Add(this);
						this._Id_Kategorii = value.Id;
					}
					else
					{
						this._Id_Kategorii = default(int);
					}
					this.SendPropertyChanged("Tabela_Kategorie");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabela_RL_Tabela_Wydarzenia", Storage="_Tabela_RL", ThisKey="Id_Uzytkownika", OtherKey="Id", IsForeignKey=true)]
		public Tabela_RL Tabela_RL
		{
			get
			{
				return this._Tabela_RL.Entity;
			}
			set
			{
				Tabela_RL previousValue = this._Tabela_RL.Entity;
				if (((previousValue != value) 
							|| (this._Tabela_RL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tabela_RL.Entity = null;
						previousValue.Tabela_Wydarzenia.Remove(this);
					}
					this._Tabela_RL.Entity = value;
					if ((value != null))
					{
						value.Tabela_Wydarzenia.Add(this);
						this._Id_Uzytkownika = value.Id;
					}
					else
					{
						this._Id_Uzytkownika = default(int);
					}
					this.SendPropertyChanged("Tabela_RL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tabela_WydarzeniaUdostepnione(Tabela_WydarzeniaUdostepnione entity)
		{
			this.SendPropertyChanging();
			entity.Tabela_Wydarzenia = this;
		}
		
		private void detach_Tabela_WydarzeniaUdostepnione(Tabela_WydarzeniaUdostepnione entity)
		{
			this.SendPropertyChanging();
			entity.Tabela_Wydarzenia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabela_WydarzeniaUdostepnione")]
	public partial class Tabela_WydarzeniaUdostepnione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Id_Wydarzenia;
		
		private int _Id_Uzytkownika;
		
		private EntityRef<Tabela_RL> _Tabela_RL;
		
		private EntityRef<Tabela_Wydarzenia> _Tabela_Wydarzenia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnId_WydarzeniaChanging(int value);
    partial void OnId_WydarzeniaChanged();
    partial void OnId_UzytkownikaChanging(int value);
    partial void OnId_UzytkownikaChanged();
    #endregion
		
		public Tabela_WydarzeniaUdostepnione()
		{
			this._Tabela_RL = default(EntityRef<Tabela_RL>);
			this._Tabela_Wydarzenia = default(EntityRef<Tabela_Wydarzenia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Wydarzenia", DbType="Int NOT NULL")]
		public int Id_Wydarzenia
		{
			get
			{
				return this._Id_Wydarzenia;
			}
			set
			{
				if ((this._Id_Wydarzenia != value))
				{
					if (this._Tabela_Wydarzenia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_WydarzeniaChanging(value);
					this.SendPropertyChanging();
					this._Id_Wydarzenia = value;
					this.SendPropertyChanged("Id_Wydarzenia");
					this.OnId_WydarzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Uzytkownika", DbType="Int NOT NULL")]
		public int Id_Uzytkownika
		{
			get
			{
				return this._Id_Uzytkownika;
			}
			set
			{
				if ((this._Id_Uzytkownika != value))
				{
					if (this._Tabela_RL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_UzytkownikaChanging(value);
					this.SendPropertyChanging();
					this._Id_Uzytkownika = value;
					this.SendPropertyChanged("Id_Uzytkownika");
					this.OnId_UzytkownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabela_RL_Tabela_WydarzeniaUdostepnione", Storage="_Tabela_RL", ThisKey="Id_Uzytkownika", OtherKey="Id", IsForeignKey=true)]
		public Tabela_RL Tabela_RL
		{
			get
			{
				return this._Tabela_RL.Entity;
			}
			set
			{
				Tabela_RL previousValue = this._Tabela_RL.Entity;
				if (((previousValue != value) 
							|| (this._Tabela_RL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tabela_RL.Entity = null;
						previousValue.Tabela_WydarzeniaUdostepnione.Remove(this);
					}
					this._Tabela_RL.Entity = value;
					if ((value != null))
					{
						value.Tabela_WydarzeniaUdostepnione.Add(this);
						this._Id_Uzytkownika = value.Id;
					}
					else
					{
						this._Id_Uzytkownika = default(int);
					}
					this.SendPropertyChanged("Tabela_RL");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabela_Wydarzenia_Tabela_WydarzeniaUdostepnione", Storage="_Tabela_Wydarzenia", ThisKey="Id_Wydarzenia", OtherKey="Id", IsForeignKey=true)]
		public Tabela_Wydarzenia Tabela_Wydarzenia
		{
			get
			{
				return this._Tabela_Wydarzenia.Entity;
			}
			set
			{
				Tabela_Wydarzenia previousValue = this._Tabela_Wydarzenia.Entity;
				if (((previousValue != value) 
							|| (this._Tabela_Wydarzenia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tabela_Wydarzenia.Entity = null;
						previousValue.Tabela_WydarzeniaUdostepnione.Remove(this);
					}
					this._Tabela_Wydarzenia.Entity = value;
					if ((value != null))
					{
						value.Tabela_WydarzeniaUdostepnione.Add(this);
						this._Id_Wydarzenia = value.Id;
					}
					else
					{
						this._Id_Wydarzenia = default(int);
					}
					this.SendPropertyChanged("Tabela_Wydarzenia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
